### ISSUE TITLE
bug: urllib error mkdocs during build

### ISSUE THREAD

**Issue by c2tz** [c2tz/c2tz.li#58]
here is the vercel logs :

```
[00:50:30.425] Running build in Washington, D.C., USA (East) – iad1
[00:50:30.534] Cloning github.com/c2tz/c2tz.li (Branch: dependabot/pip/develop/urllib3-2.2.1, Commit: 166d9dc)
[00:50:30.778] Cloning completed: 243.73ms
[00:50:31.402] Restored build cache
[00:50:31.478] Running "vercel build"
[00:50:31.960] Vercel CLI 33.7.0
[00:50:32.558] Running "install" command: `pip install -r requirements.txt`...
[00:50:33.178] Collecting mkdocs==1.5.3 (from -r requirements.txt (line 1))
[00:50:33.198]   Downloading mkdocs-1.5.3-py3-none-any.whl.metadata (6.2 kB)
[00:50:33.324] Collecting mkdocs-material==9.5.8 (from -r requirements.txt (line 2))
[00:50:33.330]   Downloading mkdocs_material-9.5.8-py3-none-any.whl.metadata (16 kB)
[00:50:33.359] Collecting mkdocs-git-committers-plugin-2==2.3.0 (from -r requirements.txt (line 3))
[00:50:33.367]   Downloading mkdocs_git_committers_plugin_2-2.3.0-py3-none-any.whl.metadata (9.6 kB)
[00:50:33.399] Collecting mkdocs-git-revision-date-localized-plugin==1.2.4 (from -r requirements.txt (line 4))
[00:50:33.406]   Downloading mkdocs_git_revision_date_localized_plugin-1.2.4-py3-none-any.whl.metadata (4.8 kB)
[00:50:33.425] Collecting mkdocs-glightbox==0.3.7 (from -r requirements.txt (line 5))
[00:50:33.431]   Downloading mkdocs_glightbox-0.3.7-py3-none-any.whl.metadata (4.9 kB)
[00:50:33.451] Collecting mkdocs-material-extensions==1.3.1 (from -r requirements.txt (line 6))
[00:50:33.457]   Downloading mkdocs_material_extensions-1.3.1-py3-none-any.whl.metadata (6.9 kB)
[00:50:33.504] Collecting pymdown-extensions==10.7.1 (from -r requirements.txt (line 7))
[00:50:33.509]   Downloading pymdown_extensions-10.7.1-py3-none-any.whl.metadata (3.0 kB)
[00:50:33.538] Collecting python-dateutil==2.8.2 (from -r requirements.txt (line 8))
[00:50:33.543]   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl.metadata (8.2 kB)
[00:50:33.599] Collecting urllib3==2.2.1 (from -r requirements.txt (line 9))
[00:50:33.604]   Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
[00:50:33.670] Collecting click>=7.0 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.677]   Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
[00:50:33.696] Collecting ghp-import>=1.0 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.701]   Downloading ghp_import-2.1.0-py3-none-any.whl.metadata (7.2 kB)
[00:50:33.774] Collecting importlib-metadata>=4.3 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.779]   Downloading importlib_metadata-7.1.0-py3-none-any.whl.metadata (4.7 kB)
[00:50:33.807] Collecting jinja2>=2.11.1 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.812]   Downloading Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
[00:50:33.843] Collecting markdown>=3.2.1 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.849]   Downloading Markdown-3.6-py3-none-any.whl.metadata (7.0 kB)
[00:50:33.917] Collecting markupsafe>=2.0.1 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.922]   Downloading MarkupSafe-2.1.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
[00:50:33.941] Collecting mergedeep>=1.3.4 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.946]   Downloading mergedeep-1.3.4-py3-none-any.whl.metadata (4.3 kB)
[00:50:33.979] Collecting packaging>=20.5 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:33.984]   Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
[00:50:34.004] Collecting pathspec>=0.11.1 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:34.009]   Downloading pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
[00:50:34.043] Collecting platformdirs>=2.2.0 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:34.048]   Downloading platformdirs-4.2.0-py3-none-any.whl.metadata (11 kB)
[00:50:34.068] Collecting pyyaml-env-tag>=0.1 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:34.074]   Downloading pyyaml_env_tag-0.1-py3-none-any.whl.metadata (4.1 kB)
[00:50:34.126] Collecting pyyaml>=5.1 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:34.131]   Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
[00:50:34.194] Collecting watchdog>=2.0 (from mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:34.199]   Downloading watchdog-4.0.0-py3-none-manylinux2014_x86_64.whl.metadata (37 kB)
[00:50:34.247] Collecting babel~=2.10 (from mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:34.252]   Downloading Babel-2.14.0-py3-none-any.whl.metadata (1.6 kB)
[00:50:34.281] Collecting colorama~=0.4 (from mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:34.286]   Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
[00:50:34.322] Collecting paginate~=0.5 (from mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:34.326]   Downloading paginate-0.5.6.tar.gz (12 kB)
[00:50:34.337]   Installing build dependencies: started
[00:50:35.790]   Installing build dependencies: finished with status 'done'
[00:50:35.792]   Getting requirements to build wheel: started
[00:50:35.947]   Getting requirements to build wheel: finished with status 'done'
[00:50:35.950]   Installing backend dependencies: started
[00:50:36.545]   Installing backend dependencies: finished with status 'done'
[00:50:36.546]   Preparing metadata (pyproject.toml): started
[00:50:36.728]   Preparing metadata (pyproject.toml): finished with status 'done'
[00:50:36.767] Collecting pygments~=2.16 (from mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:36.772]   Downloading pygments-2.17.2-py3-none-any.whl.metadata (2.6 kB)
[00:50:37.255] Collecting regex>=2022.4 (from mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:37.261]   Downloading regex-2023.12.25-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
[00:50:37.267]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 12.6 MB/s eta 0:00:00
[00:50:37.315] Collecting requests~=2.26 (from mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:37.320]   Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
[00:50:37.374] Collecting gitpython (from mkdocs-git-committers-plugin-2==2.3.0->-r requirements.txt (line 3))
[00:50:37.379]   Downloading GitPython-3.1.43-py3-none-any.whl.metadata (13 kB)
[00:50:37.463] Collecting pytz (from mkdocs-git-revision-date-localized-plugin==1.2.4->-r requirements.txt (line 4))
[00:50:37.468]   Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
[00:50:37.512] Collecting six>=1.5 (from python-dateutil==2.8.2->-r requirements.txt (line 8))
[00:50:37.517]   Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[00:50:37.650] Collecting zipp>=0.5 (from importlib-metadata>=4.3->mkdocs==1.5.3->-r requirements.txt (line 1))
[00:50:37.656]   Downloading zipp-3.18.1-py3-none-any.whl.metadata (3.5 kB)
[00:50:37.876] Collecting charset-normalizer<4,>=2 (from requests~=2.26->mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:37.899]   Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
[00:50:37.934] Collecting idna<4,>=2.5 (from requests~=2.26->mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:37.944]   Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
[00:50:37.984] Collecting certifi>=2017.4.17 (from requests~=2.26->mkdocs-material==9.5.8->-r requirements.txt (line 2))
[00:50:38.001]   Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
[00:50:38.067] Collecting gitdb<5,>=4.0.1 (from gitpython->mkdocs-git-committers-plugin-2==2.3.0->-r requirements.txt (line 3))
[00:50:38.072]   Downloading gitdb-4.0.11-py3-none-any.whl.metadata (1.2 kB)
[00:50:38.124] Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->mkdocs-git-committers-plugin-2==2.3.0->-r requirements.txt (line 3))
[00:50:38.130]   Downloading smmap-5.0.1-py3-none-any.whl.metadata (4.3 kB)
[00:50:38.193] Downloading mkdocs-1.5.3-py3-none-any.whl (3.7 MB)
[00:50:38.219]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 154.0 MB/s eta 0:00:00
[00:50:38.228] Downloading mkdocs_material-9.5.8-py3-none-any.whl (8.7 MB)
[00:50:38.283]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 165.5 MB/s eta 0:00:00
[00:50:38.292] Downloading mkdocs_git_committers_plugin_2-2.3.0-py3-none-any.whl (10 kB)
[00:50:38.299] Downloading mkdocs_git_revision_date_localized_plugin-1.2.4-py3-none-any.whl (21 kB)
[00:50:38.306] Downloading mkdocs_glightbox-0.3.7-py3-none-any.whl (30 kB)
[00:50:38.313] Downloading mkdocs_material_extensions-1.3.1-py3-none-any.whl (8.7 kB)
[00:50:38.323] Downloading pymdown_extensions-10.7.1-py3-none-any.whl (250 kB)
[00:50:38.329]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.8/250.8 kB 73.6 MB/s eta 0:00:00
[00:50:38.334] Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
[00:50:38.340]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 71.7 MB/s eta 0:00:00
[00:50:38.344] Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
[00:50:38.349]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 43.7 MB/s eta 0:00:00
[00:50:38.358] Downloading Babel-2.14.0-py3-none-any.whl (11.0 MB)
[00:50:38.455]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 111.9 MB/s eta 0:00:00
[00:50:38.460] Downloading click-8.1.7-py3-none-any.whl (97 kB)
[00:50:38.465]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 35.8 MB/s eta 0:00:00
[00:50:38.470] Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
[00:50:38.477] Downloading ghp_import-2.1.0-py3-none-any.whl (11 kB)
[00:50:38.484] Downloading importlib_metadata-7.1.0-py3-none-any.whl (24 kB)
[00:50:38.491] Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
[00:50:38.496]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.2/133.2 kB 48.3 MB/s eta 0:00:00
[00:50:38.501] Downloading Markdown-3.6-py3-none-any.whl (105 kB)
[00:50:38.507]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 35.2 MB/s eta 0:00:00
[00:50:38.512] Downloading MarkupSafe-2.1.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
[00:50:38.518] Downloading mergedeep-1.3.4-py3-none-any.whl (6.4 kB)
[00:50:38.524] Downloading packaging-24.0-py3-none-any.whl (53 kB)
[00:50:38.528]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 25.0 MB/s eta 0:00:00
[00:50:38.533] Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
[00:50:38.540] Downloading platformdirs-4.2.0-py3-none-any.whl (17 kB)
[00:50:38.546] Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
[00:50:38.556]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 146.0 MB/s eta 0:00:00
[00:50:38.562] Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
[00:50:38.571]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 738.9/738.9 kB 118.1 MB/s eta 0:00:00
[00:50:38.576] Downloading pyyaml_env_tag-0.1-py3-none-any.whl (3.9 kB)
[00:50:38.583] Downloading regex-2023.12.25-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (773 kB)
[00:50:38.592]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 773.4/773.4 kB 115.4 MB/s eta 0:00:00
[00:50:38.597] Downloading requests-2.31.0-py3-none-any.whl (62 kB)
[00:50:38.602]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 23.1 MB/s eta 0:00:00
[00:50:38.607] Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
[00:50:38.614] Downloading watchdog-4.0.0-py3-none-manylinux2014_x86_64.whl (82 kB)
[00:50:38.619]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.0/83.0 kB 28.2 MB/s eta 0:00:00
[00:50:38.624] Downloading GitPython-3.1.43-py3-none-any.whl (207 kB)
[00:50:38.630]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 61.2 MB/s eta 0:00:00
[00:50:38.636] Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
[00:50:38.643]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 102.1 MB/s eta 0:00:00
[00:50:38.649] Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
[00:50:38.654]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 60.5 MB/s eta 0:00:00
[00:50:38.660] Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
[00:50:38.666]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.3/142.3 kB 49.4 MB/s eta 0:00:00
[00:50:38.675] Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
[00:50:38.680]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 24.5 MB/s eta 0:00:00
[00:50:38.689] Downloading idna-3.6-py3-none-any.whl (61 kB)
[00:50:38.693]    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 28.9 MB/s eta 0:00:00
[00:50:38.698] Downloading zipp-3.18.1-py3-none-any.whl (8.2 kB)
[00:50:38.707] Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
[00:50:38.940] Building wheels for collected packages: paginate
[00:50:38.942]   Building wheel for paginate (pyproject.toml): started
[00:50:39.154]   Building wheel for paginate (pyproject.toml): finished with status 'done'
[00:50:39.155]   Created wheel for paginate: filename=paginate-0.5.6-py3-none-any.whl size=12667 sha256=f9d644381e82cf1807c1702b8b687f231147e7f1e7637ca24fd91d34707e617c
[00:50:39.155]   Stored in directory: /vercel/.cache/pip/wheels/23/55/a5/a67625e58f39c2e16c2f4ef90ed2d1bcc9cb0eb7b3945a73fd
[00:50:39.158] Successfully built paginate
[00:50:39.529] Installing collected packages: pytz, paginate, mkdocs-glightbox, zipp, watchdog, urllib3, smmap, six, regex, pyyaml, pygments, platformdirs, pathspec, packaging, mkdocs-material-extensions, mergedeep, markupsafe, idna, colorama, click, charset-normalizer, certifi, babel, requests, pyyaml-env-tag, python-dateutil, jinja2, importlib-metadata, gitdb, markdown, gitpython, ghp-import, pymdown-extensions, mkdocs, mkdocs-material, mkdocs-git-revision-date-localized-plugin, mkdocs-git-committers-plugin-2
[00:50:45.068] Successfully installed babel-2.14.0 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 ghp-import-2.1.0 gitdb-4.0.11 gitpython-3.1.43 idna-3.6 importlib-metadata-7.1.0 jinja2-3.1.3 markdown-3.6 markupsafe-2.1.5 mergedeep-1.3.4 mkdocs-1.5.3 mkdocs-git-committers-plugin-2-2.3.0 mkdocs-git-revision-date-localized-plugin-1.2.4 mkdocs-glightbox-0.3.7 mkdocs-material-9.5.8 mkdocs-material-extensions-1.3.1 packaging-24.0 paginate-0.5.6 pathspec-0.12.1 platformdirs-4.2.0 pygments-2.17.2 pymdown-extensions-10.7.1 python-dateutil-2.8.2 pytz-2024.1 pyyaml-6.0.1 pyyaml-env-tag-0.1 regex-2023.12.25 requests-2.31.0 six-1.16.0 smmap-5.0.1 urllib3-2.2.1 watchdog-4.0.0 zipp-3.18.1
[00:50:45.068] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[00:50:45.800] Traceback (most recent call last):
[00:50:45.801]   File "/usr/local/bin/mkdocs", line 8, in <module>
[00:50:45.801]     sys.exit(cli())
[00:50:45.801]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
[00:50:45.801]     return self.main(*args, **kwargs)
[00:50:45.801]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
[00:50:45.801]     rv = self.invoke(ctx)
[00:50:45.802]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
[00:50:45.802]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[00:50:45.802]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
[00:50:45.802]     return ctx.invoke(self.callback, **ctx.params)
[00:50:45.802]   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
[00:50:45.802]     return __callback(*args, **kwargs)
[00:50:45.802]   File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 283, in build_command
[00:50:45.802]     cfg = config.load_config(**kwargs)
[00:50:45.802]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/base.py", line 378, in load_config
[00:50:45.803]     errors, warnings = cfg.validate()
[00:50:45.803]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/base.py", line 230, in validate
[00:50:45.803]     run_failed, run_warnings = self._validate()
[00:50:45.804]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/base.py", line 188, in _validate
[00:50:45.804]     self[key] = config_option.validate(value)
[00:50:45.804]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 182, in validate
[00:50:45.804]     return self.run_validation(value)
[00:50:45.804]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 1064, in run_validation
[00:50:45.804]     self.load_plugin_with_namespace(name, cfg)
[00:50:45.804]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 1102, in load_plugin_with_namespace
[00:50:45.804]     return (name, self.load_plugin(name, config))
[00:50:45.804]   File "/usr/local/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 1120, in load_plugin
[00:50:45.804]     plugin_cls = self.installed_plugins[name].load()
[00:50:45.804]   File "/usr/local/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 184, in load
[00:50:45.804]     module = import_module(match.group('module'))
[00:50:45.804]   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
[00:50:45.804]     return _bootstrap._gcd_import(name[level:], package, level)
[00:50:45.804]   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[00:50:45.805]   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[00:50:45.805]   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[00:50:45.805]   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[00:50:45.805]   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[00:50:45.805]   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[00:50:45.805]   File "/usr/local/lib/python3.9/site-packages/mkdocs_git_committers_plugin_2/plugin.py", line 12, in <module>
[00:50:45.805]     import requests, json
[00:50:45.805]   File "/usr/local/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
[00:50:45.805]     import urllib3
[00:50:45.805]   File "/usr/local/lib/python3.9/site-packages/urllib3/__init__.py", line 42, in <module>
[00:50:45.805]     raise ImportError(
[00:50:45.805] ImportError: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168
[00:50:45.858] Error: Command "mkdocs build" exited with 1
[00:50:46.090] 
```

**Comment by c2tz** [comment]
https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#common-upgrading-issues

**Comment by c2tz** [comment]
vercel seems to be the problem . i should found a workarround or prepare a migration to gh page

**Comment by c2tz** [comment]
migrated to gh page ✅
